/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1e1b19",
        "error-container": "#ffdad6",
        "surface-variant": "#e9e1dd",
        "on-secondary-container": "#785a1a",
        "surface-dim": "#e0d8d5",
        "secondary": "#775a19",
        "inverse-primary": "#ffb3b6",
        "on-secondary": "#ffffff",
        "outline": "#867273",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffdea5",
        "surface-container": "#f4ece8",
        "tertiary": "#290009",
        "on-tertiary-fixed-variant": "#822438",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb2bb",
        "inverse-surface": "#33302d",
        "secondary-container": "#fed488",
        "on-secondary-fixed": "#261900",
        "tertiary-fixed": "#ffd9dc",
        "on-primary-fixed": "#3d040e",
        "surface": "#fff8f5",
        "on-surface-variant": "#544343",
        "on-secondary-fixed-variant": "#5d4201",
        "inverse-on-surface": "#f7efeb",
        "primary-fixed-dim": "#ffb3b6",
        "on-tertiary-container": "#da677a",
        "tertiary-container": "#510019",
        "on-surface": "#1e1b19",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#e9c176",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#763037",
        "background": "#fff8f5",
        "outline-variant": "#d9c1c1",
        "surface-container-high": "#eee7e3",
        "on-tertiary-fixed": "#400012",
        "primary": "#2a0006",
        "primary-container": "#4a0e17",
        "primary-fixed": "#ffdada",
        "surface-tint": "#93474d",
        "surface-container-highest": "#e9e1dd",
        "surface-container-low": "#faf2ee",
        "on-primary": "#ffffff",
        "on-primary-container": "#ca7379",
        "surface-bright": "#fff8f5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xs": "0.5rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "gutter-desktop": "2.5rem",
        "margin-desktop": "4rem",
        "space-2xs": "0.25rem",
        "space-xl": "2rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.75rem",
        "space-4xl": "6rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem"
      },
      fontFamily: {
        "headline-md": ["Playfair Display", "serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-editorial": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Playfair Display", "serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"]
      },
      fontSize: {
        "headline-md": ["30px", { lineHeight: "38px", letterSpacing: "0em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "title-editorial": ["18px", { lineHeight: "26px", letterSpacing: "0.04em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.14em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "68px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
